SELECT BCP.*
	,A.MONTO AS PROVICIONES_EP
FROM (
	SELECT DISTINCT LOB_OBRA_V.emp_cod
		,LOB_OBRA_V.obra_cod
		,IDCENTCOSTO AS INVTID
		,LEFT(CONVERT(VARCHAR, convert(DATE, IConstruye.dbo.ESTADOPAGO.FECHACREACION, 111), 112), 6) AS PERIODO_CREACION
		,IConstruye.dbo.ESTADOPAGO.MONTOPAGODOC * IConstruye.dbo.ESTADOPAGO.TASACAMBIO AS MONTO
	FROM IConstruye.dbo.ESTADOPAGOLNDISTRIBUCION
	RIGHT OUTER JOIN IConstruye.dbo.ESTADOPAGOLINEAS ON (
			IConstruye.dbo.ESTADOPAGOLINEAS.IDDOC = IConstruye.dbo.ESTADOPAGOLNDISTRIBUCION.IDESTADOPAGO
			AND IConstruye.dbo.ESTADOPAGOLINEAS.IDLINEA = IConstruye.dbo.ESTADOPAGOLNDISTRIBUCION.IDESTADOPAGOLINEA
			)
	RIGHT OUTER JOIN IConstruye.dbo.ESTADOPAGO ON (IConstruye.dbo.ESTADOPAGO.IDDOC = IConstruye.dbo.ESTADOPAGOLINEAS.IDDOC)
	RIGHT OUTER JOIN IConstruye.dbo.FACTURACOMPRADOR ON (IConstruye.dbo.FACTURACOMPRADOR.IDDOC = IConstruye.dbo.ESTADOPAGO.IDFACTURACOMPRADOR)
	INNER JOIN (
		SELECT cpnyid + '-' + refnbr AS referencia
			,*
		FROM doc_apdoc
		) Doc_apdoc ON (IConstruye.dbo.FACTURACOMPRADOR.FOLIOUNICO = Doc_apdoc.referencia)
	INNER JOIN IConstruye.dbo.ESTADOSDOC ON (IConstruye.dbo.ESTADOSDOC.IDESTADODOC = IConstruye.dbo.ESTADOPAGO.IDESTADODOC)
	INNER JOIN IConstruye.dbo.SUBCONTRATOS ON (IConstruye.dbo.ESTADOPAGO.IDSUBCONTRATO = IConstruye.dbo.SUBCONTRATOS.IDDOC)
	INNER JOIN IConstruye.dbo.RAZONSOCIAL ON (IConstruye.dbo.RAZONSOCIAL.RUT = IConstruye.dbo.SUBCONTRATOS.RUTC)
	INNER JOIN IConstruye.dbo.ORGC ON (IConstruye.dbo.ORGC.IDORGC = IConstruye.dbo.SUBCONTRATOS.IDORGC)
	INNER JOIN (
		SELECT b.*
		FROM Iconstruye.dbo.ORGC a
			,BxO_DATA.dbo.LOB_OBRA_V b
		WHERE a.codigo = b.obra_cod
		) LOB_OBRA_V ON (IConstruye.dbo.ORGC.CODIGO = LOB_OBRA_V.obra_cod)
	RIGHT OUTER JOIN IConstruye.dbo.SUBCONTCONSOLIDADO ON (IConstruye.dbo.SUBCONTRATOS.IDDOCORIGEN = IConstruye.dbo.SUBCONTCONSOLIDADO.IDDOC)
	INNER JOIN IConstruye.dbo.ESTADOPAGOHISTORICO ON (
			IConstruye.dbo.ESTADOPAGO.IDESTADODOC = IConstruye.dbo.ESTADOPAGOHISTORICO.IDESTADODOC
			AND IConstruye.dbo.ESTADOPAGO.IDDOC = IConstruye.dbo.ESTADOPAGOHISTORICO.IDESTADOPAGO
			)
	WHERE (Doc_apdoc.apdoc_type = 'D')
		AND (
			--IConstruye.dbo.RAZONSOCIAL.RAZONSOCIAL = 'ICIL-ICAFAL S.A'
			LOB_OBRA_V.emp_cod IN (
				'0201'
				,'0202'
				,'0206'
				)
			AND IConstruye.dbo.ESTADOSDOC.DESCRIPCIONC IN (
				'EstadoPago Aprobado '
				,'EstadoPago PorAsociar '
				,'EstadoPago Asociado Factura '
				,'EstadoPago Pagado'
				)
			AND IConstruye.dbo.ESTADOPAGOLNDISTRIBUCION.IDCENTCOSTO <> '05154'
			AND IConstruye.dbo.ESTADOPAGO.CONIVA = 1
			AND LEFT(CONVERT(VARCHAR, convert(DATE, IConstruye.dbo.ESTADOPAGO.FECHACREACION, 111), 112), 6) BETWEEN '201801'
				AND '202002'
					--AND Doc_apdoc.PerPost = '202002'
			AND LEFT(CONVERT(VARCHAR, convert(DATE, IConstruye.dbo.ESTADOPAGO.FECHACREACION, 111), 112), 6) != LEFT(CONVERT(VARCHAR, convert(DATE, IConstruye.dbo.FACTURACOMPRADOR.FECHAEMISION, 111), 112), 6) 
			)
	--AND convert(DATE, IConstruye.dbo.FACTURACOMPRADOR.FECHAEMISION, 111) >= '01/02/2020'
	GROUP BY LOB_OBRA_V.obra_cod
		,Doc_apdoc.PerPost
		,LOB_OBRA_V.obra_descripcion
		,IConstruye.dbo.ESTADOPAGO.NUMDOC
		,IConstruye.dbo.SUBCONTCONSOLIDADO.EMPVRAZONSOCIAL
		,convert(DATE, IConstruye.dbo.ESTADOPAGO.FECHAAPROBACION, 111)
		,IConstruye.dbo.ESTADOSDOC.DESCRIPCIONC
		,CONVERT(VARCHAR(4), IConstruye.dbo.ESTADOPAGO.FECHACREACION, 102) + CONVERT(VARCHAR(2), IConstruye.dbo.ESTADOPAGO.FECHACREACION, 110)
		,CASE 
			WHEN IConstruye.dbo.SUBCONTRATOS.RETIENEIVA = '0'
				THEN 'SI'
			ELSE 'NO'
			END
		,convert(DATE, IConstruye.dbo.ESTADOPAGO.FECHACREACION, 111)
		,IConstruye.dbo.ESTADOPAGO.MONTOPAGODOC * IConstruye.dbo.ESTADOPAGO.TASACAMBIO
		,IConstruye.dbo.SUBCONTRATOS.RUTORGV
		,IConstruye.dbo.ESTADOPAGO.CONIVA
		,convert(DATE, IConstruye.dbo.FACTURACOMPRADOR.FECHAEMISION, 111)
		,LOB_OBRA_V.emp_cod
		,IDCENTCOSTO
	) A
INNER JOIN BO_Calculo_Provisiones BCP ON A.emp_cod = BCP.CpnyID
	AND A.obra_cod = BCP.obra_cod
	AND A.INVTID = BCP.InsumoLOB
	AND A.PERIODO_CREACION = BCP.PerPost
WHERE BCP.PerPost = '201912'
ORDER BY 2